//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://commsvr.com/UAOOI/SemanticData/UANodeSetValidation/OPCFCTTInformationModel" +
    "ling.xsd", ClrNamespace="UAOOI.SemanticData.UANodeSetValidation.XML")]

namespace UAOOI.SemanticData.UANodeSetValidation.XML
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Tests", Namespace="http://commsvr.com/UAOOI/SemanticData/UANodeSetValidation/OPCFCTTInformationModel" +
        "ling.xsd", ItemName="TestCase")]
    [System.SerializableAttribute()]
    public class Tests : System.Collections.Generic.List<UAOOI.SemanticData.UANodeSetValidation.XML.TestCase>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestCase", Namespace="http://commsvr.com/UAOOI/SemanticData/UANodeSetValidation/OPCFCTTInformationModel" +
        "ling.xsd")]
    [System.SerializableAttribute()]
    public partial class TestCase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeClassField;
        
        private string FocusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestCaseMemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpectedResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CTT
        {
            get
            {
                return this.CTTField;
            }
            set
            {
                this.CTTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SpecLink
        {
            get
            {
                return this.SpecLinkField;
            }
            set
            {
                this.SpecLinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Step
        {
            get
            {
                return this.StepField;
            }
            set
            {
                this.StepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NodeClass
        {
            get
            {
                return this.NodeClassField;
            }
            set
            {
                this.NodeClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string Focus
        {
            get
            {
                return this.FocusField;
            }
            set
            {
                this.FocusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="TestCase", EmitDefaultValue=false, Order=5)]
        public string TestCaseMember
        {
            get
            {
                return this.TestCaseMemberField;
            }
            set
            {
                this.TestCaseMemberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ExpectedResults
        {
            get
            {
                return this.ExpectedResultsField;
            }
            set
            {
                this.ExpectedResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Reviewed
        {
            get
            {
                return this.ReviewedField;
            }
            set
            {
                this.ReviewedField = value;
            }
        }
    }
}
