//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace UAOOI.DataDiscovery.DiscoveryServices.Models {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd", IsNullable=true)]
    public partial class DomainModel {
        
        private string aliasNameField;
        
        private string domainModelUriStringField;
        
        private string domainModelGuidStringField;
        
        private string descriptionField;
        
        private SemanticsDataIndex[] semanticsDataCollectionField;
        
        private string universalAddressSpaceLocatorField;
        
        private string universalAuthorizationServerLocatorField;
        
        private TypeDictionary[] typeDictionariesField;
        
        /// <remarks/>
        public string AliasName {
            get {
                return this.aliasNameField;
            }
            set {
                this.aliasNameField = value;
            }
        }
        
        /// <remarks/>
        public string DomainModelUriString {
            get {
                return this.domainModelUriStringField;
            }
            set {
                this.domainModelUriStringField = value;
            }
        }
        
        /// <remarks/>
        public string DomainModelGuidString {
            get {
                return this.domainModelGuidStringField;
            }
            set {
                this.domainModelGuidStringField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SemanticsDataIndex[] SemanticsDataCollection {
            get {
                return this.semanticsDataCollectionField;
            }
            set {
                this.semanticsDataCollectionField = value;
            }
        }
        
        /// <remarks/>
        public string UniversalAddressSpaceLocator {
            get {
                return this.universalAddressSpaceLocatorField;
            }
            set {
                this.universalAddressSpaceLocatorField = value;
            }
        }
        
        /// <remarks/>
        public string UniversalAuthorizationServerLocator {
            get {
                return this.universalAuthorizationServerLocatorField;
            }
            set {
                this.universalAuthorizationServerLocatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TypeDictionary[] TypeDictionaries {
            get {
                return this.typeDictionariesField;
            }
            set {
                this.typeDictionariesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public partial class SemanticsDataIndex {
        
        private string symbolicNameField;
        
        private ushort indexField;
        
        private FieldMetaData[] dataSetField;
        
        /// <remarks/>
        public string SymbolicName {
            get {
                return this.symbolicNameField;
            }
            set {
                this.symbolicNameField = value;
            }
        }
        
        /// <remarks/>
        public ushort Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FieldMetaData[] DataSet {
            get {
                return this.dataSetField;
            }
            set {
                this.dataSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public partial class FieldMetaData {
        
        private ExtensionDataObject extensionDataField;
        
        private string symbolicNameField;
        
        private string processValueNameField;
        
        private UATypeInfo typeInformationField;
        
        /// <remarks/>
        public ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        public string SymbolicName {
            get {
                return this.symbolicNameField;
            }
            set {
                this.symbolicNameField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessValueName {
            get {
                return this.processValueNameField;
            }
            set {
                this.processValueNameField = value;
            }
        }
        
        /// <remarks/>
        public UATypeInfo TypeInformation {
            get {
                return this.typeInformationField;
            }
            set {
                this.typeInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public partial class ExtensionDataObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public partial class LocalizedText {
        
        private string localeField;
        
        private string valueField;
        
        public LocalizedText() {
            this.localeField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public partial class EnumeratedValue {
        
        private LocalizedText[] documentationField;
        
        private string nameField;
        
        private int valueField;
        
        /// <remarks/>
        public LocalizedText[] Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public partial class StructuredTypeField {
        
        private string nameField;
        
        private System.Xml.XmlQualifiedName typeNameField;
        
        private string switchFieldField;
        
        private uint switchValueField;
        
        private bool switchValueFieldSpecified;
        
        private SwitchOperand switchOperandField;
        
        private bool switchOperandFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SwitchField {
            get {
                return this.switchFieldField;
            }
            set {
                this.switchFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint SwitchValue {
            get {
                return this.switchValueField;
            }
            set {
                this.switchValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SwitchValueSpecified {
            get {
                return this.switchValueFieldSpecified;
            }
            set {
                this.switchValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SwitchOperand SwitchOperand {
            get {
                return this.switchOperandField;
            }
            set {
                this.switchOperandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SwitchOperandSpecified {
            get {
                return this.switchOperandFieldSpecified;
            }
            set {
                this.switchOperandFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public enum SwitchOperand {
        
        /// <remarks/>
        Equals,
        
        /// <remarks/>
        GreaterThan,
        
        /// <remarks/>
        LessThan,
        
        /// <remarks/>
        GreaterThanOrEqual,
        
        /// <remarks/>
        LessThanOrEqual,
        
        /// <remarks/>
        NotEqual,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumeratedType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuredType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public partial class TypeDescription {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public partial class EnumeratedType : TypeDescription {
        
        private EnumeratedValue[] enumeratedValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EnumeratedValues")]
        public EnumeratedValue[] EnumeratedValues {
            get {
                return this.enumeratedValuesField;
            }
            set {
                this.enumeratedValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public partial class StructuredType : TypeDescription {
        
        private StructuredTypeField[] fieldField;
        
        private StructureKindEnum structureKindField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Field")]
        public StructuredTypeField[] Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public StructureKindEnum StructureKind {
            get {
                return this.structureKindField;
            }
            set {
                this.structureKindField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public enum StructureKindEnum {
        
        /// <remarks/>
        Structure,
        
        /// <remarks/>
        StructureWithOptionalFields,
        
        /// <remarks/>
        Union,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public partial class TypeDictionary {
        
        private StructuredType[] structuredTypeField;
        
        private string targetNamespaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StructuredType")]
        public StructuredType[] StructuredType {
            get {
                return this.structuredTypeField;
            }
            set {
                this.structuredTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetNamespace {
            get {
                return this.targetNamespaceField;
            }
            set {
                this.targetNamespaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public partial class UATypeInfo {
        
        private BuiltInType builtInTypeField;
        
        private int valueRankField;
        
        private int[] arrayDimensionsField;
        
        private System.Xml.XmlQualifiedName typeNameField;
        
        /// <remarks/>
        public BuiltInType BuiltInType {
            get {
                return this.builtInTypeField;
            }
            set {
                this.builtInTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ValueRank {
            get {
                return this.valueRankField;
            }
            set {
                this.valueRankField = value;
            }
        }
        
        /// <remarks/>
        public int[] ArrayDimensions {
            get {
                return this.arrayDimensionsField;
            }
            set {
                this.arrayDimensionsField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlQualifiedName TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://http://commsvr.com/UAOOI/DataDiscovery/DiscoveryServices/Models/DomainMode" +
        "l.xsd")]
    public enum BuiltInType {
        
        /// <remarks/>
        Null,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        SByte,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Int16,
        
        /// <remarks/>
        UInt16,
        
        /// <remarks/>
        Int32,
        
        /// <remarks/>
        UInt32,
        
        /// <remarks/>
        Int64,
        
        /// <remarks/>
        UInt64,
        
        /// <remarks/>
        Float,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Guid,
        
        /// <remarks/>
        ByteString,
        
        /// <remarks/>
        XmlElement,
        
        /// <remarks/>
        NodeId,
        
        /// <remarks/>
        ExpandedNodeId,
        
        /// <remarks/>
        StatusCode,
        
        /// <remarks/>
        QualifiedName,
        
        /// <remarks/>
        LocalizedText,
        
        /// <remarks/>
        ExtensionObject,
        
        /// <remarks/>
        DataValue,
        
        /// <remarks/>
        Variant,
        
        /// <remarks/>
        DiagnosticInfo,
        
        /// <remarks/>
        Enumeration,
    }
}
