//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://commsvr.com/UAOOI/SemanticData/UANetworking/Configuration/Serialization.xs" +
    "d", ClrNamespace="UAOOI.SemanticData.UANetworking.Configuration.Serialization")]

namespace UAOOI.SemanticData.UANetworking.Configuration.Serialization
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    public partial class ConfigurationData : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ConfigurationData", "http://commsvr.com/UAOOI/SemanticData/UANetworking/Configuration/Serialization.xs" +
                "d");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://commsvr.com/UAOOI/SemanticData/UANetworking/Configuration/Serialization.xs" +
        "d")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSetConfiguration", Namespace="http://commsvr.com/UAOOI/SemanticData/UANetworking/Configuration/Serialization.xs" +
        "d")]
    [System.SerializableAttribute()]
    public partial class DataSetConfiguration : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UAOOI.SemanticData.UANetworking.Configuration.Serialization.ExtensionDataObject ExtensionData1Field;
        
        private UAOOI.SemanticData.UANetworking.Configuration.Serialization.AssociationRole AssociationRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssociationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepositoryGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformationModelURIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataSymbolicNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UAOOI.SemanticData.UANetworking.Configuration.Serialization.DataMemberConfiguration[] DataSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UAOOI.SemanticData.UANetworking.Configuration.Serialization.NodeDescriptor RootField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UAOOI.SemanticData.UANetworking.Configuration.Serialization.ExtensionDataObject ExtensionData1
        {
            get
            {
                return this.ExtensionData1Field;
            }
            set
            {
                this.ExtensionData1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public UAOOI.SemanticData.UANetworking.Configuration.Serialization.AssociationRole AssociationRole
        {
            get
            {
                return this.AssociationRoleField;
            }
            set
            {
                this.AssociationRoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AssociationName
        {
            get
            {
                return this.AssociationNameField;
            }
            set
            {
                this.AssociationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RepositoryGroup
        {
            get
            {
                return this.RepositoryGroupField;
            }
            set
            {
                this.RepositoryGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string InformationModelURI
        {
            get
            {
                return this.InformationModelURIField;
            }
            set
            {
                this.InformationModelURIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DataSymbolicName
        {
            get
            {
                return this.DataSymbolicNameField;
            }
            set
            {
                this.DataSymbolicNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public UAOOI.SemanticData.UANetworking.Configuration.Serialization.DataMemberConfiguration[] DataSet
        {
            get
            {
                return this.DataSetField;
            }
            set
            {
                this.DataSetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public UAOOI.SemanticData.UANetworking.Configuration.Serialization.NodeDescriptor Root
        {
            get
            {
                return this.RootField;
            }
            set
            {
                this.RootField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NodeDescriptor", Namespace="http://commsvr.com/UAOOI/SemanticData/UANetworking/Configuration/Serialization.xs" +
        "d")]
    [System.SerializableAttribute()]
    public partial class NodeDescriptor : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BindingDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.XmlQualifiedName DataTypeField;
        
        private bool InstanceDeclarationField;
        
        private UAOOI.SemanticData.UANetworking.Configuration.Serialization.InstanceNodeClassesEnum NodeClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.XmlQualifiedName NodeIdentifierField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BindingDescription
        {
            get
            {
                return this.BindingDescriptionField;
            }
            set
            {
                this.BindingDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.XmlQualifiedName DataType
        {
            get
            {
                return this.DataTypeField;
            }
            set
            {
                this.DataTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool InstanceDeclaration
        {
            get
            {
                return this.InstanceDeclarationField;
            }
            set
            {
                this.InstanceDeclarationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public UAOOI.SemanticData.UANetworking.Configuration.Serialization.InstanceNodeClassesEnum NodeClass
        {
            get
            {
                return this.NodeClassField;
            }
            set
            {
                this.NodeClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.XmlQualifiedName NodeIdentifier
        {
            get
            {
                return this.NodeIdentifierField;
            }
            set
            {
                this.NodeIdentifierField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssociationRole", Namespace="http://commsvr.com/UAOOI/SemanticData/UANetworking/Configuration/Serialization.xs" +
        "d")]
    public enum AssociationRole : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Consumer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Producer = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataMemberConfiguration", Namespace="http://commsvr.com/UAOOI/SemanticData/UANetworking/Configuration/Serialization.xs" +
        "d")]
    [System.SerializableAttribute()]
    public partial class DataMemberConfiguration : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UAOOI.SemanticData.UANetworking.Configuration.Serialization.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolicNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessValueNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceEncodingField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UAOOI.SemanticData.UANetworking.Configuration.Serialization.ExtensionDataObject ExtensionData1
        {
            get
            {
                return this.ExtensionData1Field;
            }
            set
            {
                this.ExtensionData1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SymbolicName
        {
            get
            {
                return this.SymbolicNameField;
            }
            set
            {
                this.SymbolicNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProcessValueName
        {
            get
            {
                return this.ProcessValueNameField;
            }
            set
            {
                this.ProcessValueNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SourceEncoding
        {
            get
            {
                return this.SourceEncodingField;
            }
            set
            {
                this.SourceEncodingField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstanceNodeClassesEnum", Namespace="http://commsvr.com/UAOOI/SemanticData/UANetworking/Configuration/Serialization.xs" +
        "d")]
    public enum InstanceNodeClassesEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Object = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Variable = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Method = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        View = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDefined = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageHandlerConfiguration", Namespace="http://commsvr.com/UAOOI/SemanticData/UANetworking/Configuration/Serialization.xs" +
        "d")]
    [System.SerializableAttribute()]
    public partial class MessageHandlerConfiguration : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UAOOI.SemanticData.UANetworking.Configuration.Serialization.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UAOOI.SemanticData.UANetworking.Configuration.Serialization.ArrayOfString AssociationNamesArrayOfStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.XmlElement ConfigurationField;
        
        private UAOOI.SemanticData.UANetworking.Configuration.Serialization.AssociationRole TransportRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UAOOI.SemanticData.UANetworking.Configuration.Serialization.ArrayOfString AssociationNamesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UAOOI.SemanticData.UANetworking.Configuration.Serialization.ExtensionDataObject ExtensionData1
        {
            get
            {
                return this.ExtensionData1Field;
            }
            set
            {
                this.ExtensionData1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public UAOOI.SemanticData.UANetworking.Configuration.Serialization.ArrayOfString AssociationNamesArrayOfString
        {
            get
            {
                return this.AssociationNamesArrayOfStringField;
            }
            set
            {
                this.AssociationNamesArrayOfStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Xml.XmlElement Configuration
        {
            get
            {
                return this.ConfigurationField;
            }
            set
            {
                this.ConfigurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public UAOOI.SemanticData.UANetworking.Configuration.Serialization.AssociationRole TransportRole
        {
            get
            {
                return this.TransportRoleField;
            }
            set
            {
                this.TransportRoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public UAOOI.SemanticData.UANetworking.Configuration.Serialization.ArrayOfString AssociationNames
        {
            get
            {
                return this.AssociationNamesField;
            }
            set
            {
                this.AssociationNamesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://commsvr.com/UAOOI/SemanticData/UANetworking/Configuration/Serialization.xs" +
        "d", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
}
